[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@openzeppelin/=/home/jay/supersim-scripts/node_modules/@openzeppelin",
  "src/=/home/jay/supersim-scripts/lib/optimism/packages/contracts-bedrock/src"
  
]


evm_version = "cancun"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
